name: Pack Release

on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Beet
        run: |
          pip install -r requirements.txt

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Zip packs
        run: |
          beet build
          mv dist/exported_data_pack.zip mc-codex-dp-${GITHUB_REF_NAME}.zip
          mv dist/exported_resource_pack.zip mc-codex-rp-${GITHUB_REF_NAME}.zip

      - name: Zip mcdoc
        run: |
          zip -r dist/codex-mcdoc.zip mcdoc

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.zip

      - name: Send notification to Discord
        if: always()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: "[${{ github.event.repository.name }}] automated release"
          embed-url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: |
            **Tag**: ${{ github.ref_name }}
            **Status**: ${{ job.status }}
          embed-timestamp: ${{ github.event.release.published_at }}
          embed-color: 0x66ee66
